# Generated by Django 3.2 on 2021-11-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20211125_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='owner',
            new_name='customer',
        ),
    ]
