# Generated by Django 3.2 on 2021-11-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_rename_owner_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
