# Generated by Django 3.2 on 2021-12-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0014_auto_20211206_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingpaymentcustomer',
            name='card_number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='shippingpaymentorder',
            name='card_number',
            field=models.PositiveBigIntegerField(),
        ),
    ]
