# Generated by Django 3.2 on 2021-12-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0017_auto_20211206_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingpaymentcustomer',
            name='expiry_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='shippingpaymentorder',
            name='expiry_year',
            field=models.CharField(max_length=4),
        ),
    ]
