# Generated by Django 3.2 on 2021-12-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0021_auto_20211206_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddresscustomer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingpaymentcustomer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shippingpaymentcustomer',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='shippingpaymentorder',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
    ]
