# Generated by Django 3.2 on 2021-12-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0022_auto_20211207_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddresscustomer',
            old_name='is_active',
            new_name='active',
        ),
    ]
