# Generated by Django 3.2 on 2021-12-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0024_auto_20211209_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingpaymentcustomer',
            name='card_number',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='shippingpaymentorder',
            name='card_number',
            field=models.CharField(max_length=19),
        ),
    ]
