# Generated by Django 3.2 on 2021-12-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0025_auto_20211210_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingpaymentcustomer',
            name='card_number',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='shippingpaymentorder',
            name='card_number',
            field=models.CharField(max_length=22),
        ),
    ]
