# Generated by Django 3.2 on 2021-12-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0028_auto_20211213_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingpaymentorder',
            name='active',
        ),
    ]
