# Generated by Django 3.2 on 2021-12-23 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0030_alter_orderitem_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddressorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shippingpaymentorder',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.shippingaddressorder'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.shippingpaymentorder'),
        ),
    ]
