# Generated by Django 3.2 on 2021-12-23 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0031_auto_20211223_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Cart',
        ),
    ]
