# Generated by Django 3.2 on 2022-01-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0033_auto_20220110_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='ordered',
            new_name='delivered',
        ),
    ]
