# Generated by Django 3.2 on 2022-01-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0035_auto_20220110_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='delivered',
            new_name='complete',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
