# Generated by Django 3.2 on 2022-01-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0038_alter_cart_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
