# Generated by Django 3.2 on 2022-01-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0040_cart_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='complete',
            new_name='completely_delivered',
        ),
    ]
