# Generated by Django 4.0.2 on 2022-02-15 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_vendor_orders'),
        ('carts', '0041_rename_complete_cart_completely_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor'),
        ),
    ]
