# Generated by Django 3.2 on 2021-10-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_vendor',
            field=models.BooleanField(default=True),
        ),
    ]
