# Generated by Django 3.2 on 2021-10-21 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211019_1523'),
        ('accounts', '0004_vendor_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='storename',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shop.shop'),
        ),
    ]
