# Generated by Django 3.2 on 2021-10-28 09:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20211026_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='profile.png', upload_to=accounts.models.photo_path),
        ),
    ]
