# Generated by Django 3.2 on 2021-12-23 12:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='levi-stute-mFF39sOZSgM-unsplash.jpg', null=True, upload_to=accounts.models.photo_path),
        ),
    ]
