# Generated by Django 3.2 on 2021-12-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_vendor_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='is_vendor',
        ),
    ]
