# Generated by Django 4.0.2 on 2022-02-28 10:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_vendor_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='victor-aldabalde-HguvvRqNgxo-unsplash.jpg', upload_to=accounts.models.photo_path),
        ),
    ]
