# Generated by Django 4.0.2 on 2022-03-14 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_added', models.IntegerField(default=0)),
                ('can_add', models.BooleanField(default=False)),
                ('Group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='accounts.watchgroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
