# Generated by Django 4.0.2 on 2022-03-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watched_products', '0001_initial'),
        ('accounts', '0020_watchgroup_watchgroupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchgroup',
            name='watch_list',
            field=models.ManyToManyField(related_name='+', to='watched_products.WatchList'),
        ),
    ]
