# Generated by Django 4.0.2 on 2022-03-14 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_watchgroup_watch_list'),
        ('watched_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.watchgroup'),
        ),
    ]
