# Generated by Django 4.0.2 on 2022-03-14 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_watchedproduct'),
        ('watched_products', '0002_watchlist_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='initial_Price',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='initial_quantity',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shop.watchedproduct'),
        ),
        migrations.DeleteModel(
            name='WatchedProduct',
        ),
    ]
