# Generated by Django 4.0.2 on 2022-03-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watched_products', '0003_rename_date_added_watchlist_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
