# Generated by Django 4.0.2 on 2022-03-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watched_products', '0004_watchlist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
