# Generated by Django 4.0.2 on 2022-03-14 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('watched_products', '0005_alter_watchlist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
