# Generated by Django 4.0.2 on 2022-03-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watched_products', '0006_watchlist_content_type_watchlist_object_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('group__isnull', False), ('customer__isnull', True)), models.Q(('group__isnull', True), ('customer__isnull', False)), _connector='OR'), name='only_one_price'),
        ),
    ]
