# Generated by Django 4.0.3 on 2022-04-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watched_products', '0007_watchlist_only_one_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='product',
            new_name='products',
        ),
    ]
