# Generated by Django 4.0.3 on 2022-04-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_product_productimages'),
        ('watched_products', '0008_rename_product_watchlist_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='products',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='products',
            field=models.ManyToManyField(null=True, related_name='+', to='shop.watchedproduct'),
        ),
    ]
