# Generated by Django 4.0.3 on 2022-04-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_product_productimages'),
        ('watched_products', '0009_remove_watchlist_products_watchlist_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='products',
            field=models.ManyToManyField(related_name='+', to='shop.watchedproduct'),
        ),
    ]
