# Generated by Django 4.0.3 on 2022-04-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_remove_watchedproduct_watch_list'),
        ('watched_products', '0011_remove_watchlist_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='products',
            field=models.ManyToManyField(related_name='+', to='shop.watchedproduct'),
        ),
    ]
