# Generated by Django 4.0.3 on 2022-04-06 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_customer_watch_list'),
        ('watched_products', '0012_watchlist_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.customer'),
        ),
    ]
