# Generated by Django 4.0.3 on 2022-04-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watched_products', '0013_alter_watchlist_customer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='watchlist',
            name='only_one_price',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='group',
        ),
    ]
