# Generated by Django 4.0.3 on 2022-08-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_shop_products_shop_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='products',
        ),
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='shop', related_query_name='shop', to='shop.product'),
        ),
    ]
