# Generated by Django 3.2 on 2021-10-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='stars',
            field=models.IntegerField(max_length=10),
        ),
    ]
