# Generated by Django 3.2 on 2021-10-19 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_vendor_is_vendor'),
        ('shop', '0006_alter_productreview_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='productimages',
            field=models.ManyToManyField(to='shop.ProductImage'),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(null=True, to='shop.Product')),
                ('review', models.ManyToManyField(null=True, to='shop.ProductReview')),
                ('vendor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor')),
            ],
        ),
    ]
