# Generated by Django 3.2 on 2021-10-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211019_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='review',
            field=models.ManyToManyField(to='shop.ProductReview'),
        ),
    ]
