# Generated by Django 3.2 on 2021-10-21 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vendor_storename'),
        ('shop', '0008_auto_20211019_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shopname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='vendor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.vendor'),
        ),
    ]
