# Generated by Django 3.2 on 2021-10-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20211021_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity_available',
            new_name='stock',
        ),
    ]
