# Generated by Django 3.2 on 2021-10-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20211021_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail',
        ),
    ]
