# Generated by Django 3.2 on 2021-10-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_productimage_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='review',
        ),
    ]
