# Generated by Django 3.2 on 2021-10-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20211022_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='review',
            field=models.ManyToManyField(blank=True, to='shop.ProductReview'),
        ),
    ]
