# Generated by Django 3.2 on 2021-10-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_shop_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='user',
            new_name='customer',
        ),
    ]
