# Generated by Django 3.2 on 2021-11-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customer_profile_pic'),
        ('shop', '0019_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ManyToManyField(related_name='_shop_product_vendor_+', to='accounts.Vendor'),
        ),
    ]
