# Generated by Django 4.0.3 on 2022-03-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_watchedproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_added']},
        ),
    ]
