# Generated by Django 4.0.2 on 2022-03-21 11:36

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_product_slug_productimage_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='victor-aldabalde-HguvvRqNgxo-unsplash.jpg', upload_to=shop.models.photo_path),
        ),
    ]
