# Generated by Django 4.0.3 on 2022-03-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shopname',
            new_name='shop_name',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
