# Generated by Django 4.0.3 on 2022-03-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_rename_shopname_shop_shop_name_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_name',
            new_name='shopname',
        ),
    ]
