# Generated by Django 4.0.3 on 2022-04-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_product_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchedproduct',
            name='watch_list',
        ),
    ]
