# Generated by Django 4.0.3 on 2022-04-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_remove_watchedproduct_watch_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchedproduct',
            old_name='initial_Price',
            new_name='initial_price',
        ),
    ]
